openapi: 3.0.0
info:
  title: VoicePing Conversation api
  description: Conversation Service for VoicePing Users
  version: 0.0.3
servers:
- url: https://voiceoverping.net
  description: Conversation
- url: https://archiver.voiceoverping.net
  description: Archiver
paths:
  /v2/oauth/token:
    post:
      tags:
      - Conversation
      summary: Get Access Token
      operationId: getAccessToken
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                username: 
                  type: string
                  example: <api-user-username>
                password: 
                  type: string
                  example: <api-user-password>
                client_id: 
                  type: string
                  example: 2359media
                client_secret: 
                  type: string
                  example: 2359admin
                grant_type: 
                  type: string
                  example: password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccessTokenResponse'
  /api/v2/allchannels:
    get:
      tags:
      - Conversation
      summary: List Channels
      operationId: listChannels
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listChannelsResponse'
  /api/v2/users:
    get:
      tags:
      - Conversation
      summary: List Users
      operationId: listUsers
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usersResponse'
  /api/archive/group:
    post:
      tags:
      - Conversation
      summary:  Get Channel’s Conversation History
      operationId:  getChannelConversationHistory
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                  group_id: 
                    type: string
                    example: 2815
                  start_time: 
                    type: integer
                    example: 1506272400000
                  end_time:
                    type: integer
                    example: 1506358800000
                  timezone_offset:
                    type: integer
                    example: 8
                  webhook_url: 
                    type: string
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conversationHistoryResponse'
  /api/users/private:
    post:
      tags:
      - Archiver
      summary:  Get User’s Private Conversation Target
      operationId: getUsePrivateConversationTarget
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                  user_id: 
                    type: integer
                    example: 2815
                  start_time: 
                    type: integer
                    example: 1506272400000
                  end_time:
                    type: integer
                    example: 1506358800000
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/privateUserConversationHistoryResponse'
  /api/archive/private:
    post:
      tags:
      - Archiver
      summary: Get Private Conversation History 
      operationId: getPrivateConversationHistory 
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                  user_id: 
                    type: array
                    items:
                      type: integer
                    example: [2815, 552]
                  start_time: 
                    type: integer
                    example: 1506272400000
                  end_time:
                    type: integer
                    example: 1506358800000
                  timezone_offset:
                    type: integer
                    example: 8
                  webhook_url: 
                    type: string
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conversationHistoryResponse'
components:
  schemas:
    getAccessTokenResponse:
      type: object
      properties:
        access_token:
          type: string
          example: <access_token>
        username:
          type: string
          example: username
        fullname:
          type: string
          example: user full_name
        uuid:
          type: string
          example: <user_uuid>
        privilege:
          type: string
          example: admin
        avatar_url:
          type: string
          example: <user_avatar_url>
        email:
          type: string
          example: user@mail.com
        company:
          type: string
          example: usercompanny.com
        phone:
          type: string
          example: null
        id:
          type: integer
          example: 5
        socket_url:
          type: string
          example: wss://5759media-router.voiceoverping.net
        status:
          type: string
          example: online
        statusValue:
          type: integer
          example: 1
        token_type:
          type: string
          example: Bearer         
    listChannelsResponse:
      type: object
      properties: 
          channels: 
            type: array
            items:
              type: object
              properties: 
                id: 
                  type: integer
                  example: 5
                name: 
                  type: string
                  example: my chanel
                users: 
                  type: array
                  items: 
                    type: object
                domain: 
                  type: string
                  example: domain.com
    usersResponse: 
      type: array
      items: 
        type: object
        properties: 
            id: 
              type: integer
              example: 55
            username:
              type: string
              example: 7705@smarttrial.com
            channels: 
              type: array
              items: 
                type: object
    conversationHistoryResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        request_id: 
          type: string
          example: hjdkawd897dad
    privateUserConversationHistoryResponse:
      type: object
      properties:
        status:
          type: string
          example: 2815
        data:
          type: array
          items: 
            type: object
            properties: 
              id: 
                type: integer
                example: 123
              username: 
                type: string
                example: john@smartwalkie.com
                        
                      
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
